### ISSUE TITLE
All Test Cases Failing : org.dbunit.dataset.NoSuchColumnException: bird.VISIBLE

### ISSUE THREAD

**Issue by akshitmahajan** [ak1801/directoryservice#2]
When executing test suite using **mvn test** or building app using **mvn clean install** all test cases getting failed with following exception:

Error stack:

INFO: Rolled back transaction for test context [DefaultTestContext@214894fc test
Class = BirdDirectoryServiceDAOImplUTest, testInstance = com.profactus.directory
.dao.BirdDirectoryServiceDAOImplUTest@33f88ab, testMethod = getById@BirdDirector
yServiceDAOImplUTest, testException = [null], mergedContextConfiguration = [Merg
edContextConfiguration@10567255 testClass = BirdDirectoryServiceDAOImplUTest, lo
cations = '{}', classes = '{class com.profactus.directory.configuration.Hibernat
eTestConfiguration}', contextInitializerClasses = '[]', activeProfiles = '{}', p
ropertySourceLocations = '{}', propertySourceProperties = '{}', contextLoader =
'org.springframework.test.context.support.DelegatingSmartContextLoader', parent
= [null]]].
Tests run: 4, Failures: 3, Errors: 0, Skipped: 1, Time elapsed: 3.694 sec <<< FA
ILURE!
setUp(com.profactus.directory.dao.BirdDirectoryServiceDAOImplUTest)  Time elapse
d: 3.171 sec  <<< FAILURE!
org.dbunit.dataset.NoSuchColumnException: bird.VISIBLE
        at org.dbunit.operation.AbstractOperation.getOperationMetaData(AbstractO
peration.java:71)
        at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOper
ation.java:130)
        at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.ja
va:67)
        at com.profactus.directory.dao.EntityDaoImplUTest.setUp(EntityDaoImplUTe
st.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocat
ionHelper.java:85)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:51
7)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:601)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWork
er.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at org.testng.TestRunner.privateRun(TestRunner.java:771)
        at org.testng.TestRunner.run(TestRunner.java:621)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
        at org.testng.SuiteRunner.run(SuiteRunner.java:259)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

**Comment by akshitmahajan** [comment]
This issue has probably occurred because something is screwed up in the test setup or the test case itself.
To fix this, need to revisit the test suite configuration and Unit Test Classes.
